echo 
Beginning Run all tdt's batch process, press enter to begin... 
pause
PC20...
pause
psExec \\10.1.10.87 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC20TDTs.bat 
PC19...
pause
psExec \\10.1.10.86 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC19TDTs.bat
PC18...
pause
psExec \\10.1.10.81 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC18TDTs.bat
PC17...
pause
psExec \\10.1.10.36 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC17TDTs.bat
PC12...
pause
psExec \\10.1.10.21 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC12TDTs.bat
PC9...
pause
psExec \\10.1.10.17 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC9TDTs.bat
PC8...
pause
psExec \\10.1.10.18 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC8TDTs.bat
PC5...
pause
psExec \\10.1.10.11 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC5TDTs.bat
PC4...
pause
psExec \\10.1.10.12 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC4TDTs.bat
PC3...
pause
psExec \\10.1.10.13 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC3TDTs.bat
PC2...
pause
psExec \\10.1.10.14 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC2TDTs.bat
PC1...
pause
psExec \\10.1.10.15 -u sclan\SMatrix -p SMatrix1! -c C:\Users\mhorstmann\Desktop\TDTbatchRunners\runPC1TDTs.bat
ALL TDT instances initialized.
Press enter to continue......
pause